#!/bin/sh

version=`./shtool version -lc -d long source/xversion.c`

# find out terminal sequences
if test ".$enable_subdir" != .yes; then
	TB=`./shtool echo -n -e %B 2>/dev/null`
	TN=`./shtool echo -n -e %b 2>/dev/null`
else
	TB=''
	TN=''
fi

#   find out package version

echo "Remaking auto-files for ${TB}Xaric${TN}, Version ${TB}${version}${TN}"

aclocal
autoheader
autoconf




