.TH "xaric" "1" "" "Alan P. Laudicina" ""
.SH "NAME"
.LP 
xaric \- Internet Relay Chat client for UNIX systems
.SH "SYNTAX"
.LP 
xaric [\fI\-b\fP] [\fI\-f\fP] [\fI\-F\fP] [\fI\-q\fP] [\fI\-a\fP] [\fI\-x\fP] [\fI\-v\fP]
.br 
[\fI\-p port\fP] [\fI\-H hostname\fP] [\fI\-r file\fP] [\fI\-n nickname\fP] [\fI\-l file\fP] [\fI\-L file\fP]
.SH "DESCRIPTION"
.LP 
Xaric is a UNIX irc client similer to BitchX or ircII. I would impress you
with a list of features, but since it has no impressive features (and lacks a few important ones) that probably is not a good idea. The whole reason for Xaric was to remove all of the bogus, broken crap and silly features from BitchX and have a nice colorful client. 
.SH "OPTIONS"
.LP 
.TP 
\fB\-H\fR <\fIhostname\fP>
Use the IP address of the specified hostname as the IP you connect to the IRC server with.  This is very common with virtual hosting.  It can also be used if gethostname(3) doesn't return a hostname.
.TP 
\fB\-p\fR <\fIport\fP>
Connect to the IRC server on the port specified instead of the default that you set in your config.h file.
.TP 
\fB\-n\fR <\fInickname\fP>
When connecting to the IRC server, use \fInickname\fP instead of the default of your UNIX login name.
.TP 
\fB\-l\fR <\fIfile\fP>
This option will let you load \fIfile\fP instead of your ~/.ircrc
.TP 
\fB\-L\fR <\fIfile\fP>
This option does the same thing as \fB\-l\fR, except in this case it also expands $ expandos
\fB\-b\fR
Load your ~/.ircrc file after you connect to the IRC server, instead of before.
.TP 
\fB\-f\fR
If your term uses flow controls (^S/^Q), run xaric with this option and it will not.
.TP 
\fB\-F\fR
Your terminal doesn't use flow controls (this is a default).
.TP 
\fB\-q\fR
Do not load your ~/.ircrc
.TP 
\fB\-a\fR
Adds default servers and command line servers to server list
.TP 
\fB\-x\fR
Run xaric in "debug" mode.
.TP 
\fB\-v\fR
Tells you about the version of xaric that you are running.
.SH "FILES"
.LP 
\fB/usr/local/bin/xaric\fR
Default location for the xaric binary
.LP 
\fB~/.ircrc\fR
Default initialization file
.SH "EXAMPLES"
.TP 
\fBxaric\fR
This is what should be tried first, it connects to the default server using the nickname $USER
.TP 
\fBxaric nickname\fR
Connect to your default IRC server with the nickname specified.
.TP 
\fBxaric nickname ircd.grateful.org\fR
Connect to the IRC server located at ircd.grateful.org with the nickname specified
.TP 
\fBxaric nickname ircd.grateful.org:6669\fR
Connect to the IRC server located on ircd.grateful.org port 6669, with the nickname specified
.TP 
\fBxaric nickname irc.efnet.net\fR
Try this if you're stumped and trying to get on EFnet
.TP 
\fBxaric nickname irc.dal.net\fR
Try this if you're stumped and trying to get on DALnet
.TP 
\fBxaric nickname ircd.grateful.org\fR
Try this if you're stumped and trying to get on UNIXNet
.TP 
\fBxaric nickname irc.undernet.org\fR
Try this if you're stumped and trying to get to UnderNet
.SH "WHAT NOW?"
We wont explain what to do once you are connected to an IRC server here.  If you're connected and you're not sure what to do, you want to visit http://www.irchelp.org/
.SH "AUTHORS"
.LP 
IRC Client: Rex G. Feany <laeos@laeos.net>
Man Page:   Alan P. Laudicina <alanp@unixpower.org>
