.TH Xaric 1L "29 October 1997"
.SH NAME
Xaric \- A client for the Internet Relay Chat system
.SH SYNOPSIS
.B xaric 
.RB [ \-c
.IR chan ]
.RB [ \-p
.IR portno ]
.RB [ \-f ]
.RB [ \-F ]
.IR [ nickname
.IR [ "server list" ]]
.RB [ \-l
.IR "filename"
.RB ]
.RB [ \-L
.IR "filename"
.RB ]
.RB [ \-a ]
.RB [ \-v ]
.RB [ \-q ]
.SH DESCRIPTION
The
.I ircII
program is a full screen, termcap based interface to Internet Relay Chat.
It gives full access to all of the normal
.I IRC
functions, plus a variety of additional options.
.SH OPTIONS
.TP
.BI \-c " chan"
Automatically join channel
.I chan .
.TP
.BI \-p " portno"
Set the port number to
.I portno
(default: 6667, the standard
.I IRC
port).
Only supply this if you connect to a server which uses a port other than 6667.
.TP
.B \-f
Use flow control (^S and ^Q) to stop/start the display.
Normally these are both bound to other functions within
.IR irc .
This switch is ignored if the
.B \ -d
switch is used.
.TP
.B \-F
Don't use flow control (^S and ^Q) to stop start the display.
.TP
.I nickname
Set the nickname
(overrides the environment variable
.BR IRCNICK ;
default: the username).
.TP
.I server
Set the list of servers with which
.B irc
will try to connect upon startup.
This list is also used by the program's
.B /server
command.
The format for lines in the list is:
.IP
.B hostname
.RB [:portno[:password[:nick]]]
.TP
.BI \-l " filename"
Selects a different file to be used as the .ircrc file for 
.B ircII.
There is no exansion of $ expandos when using this option.
The default is $HOME/.ircrc.
.TP
.BI \-L " filename"
Selects a different file to be used as the .ircrc file for
.B ircII.
Expansion of $ expandos happens with this option.  
The default is $HOME/.ircrc.
.TP
.BI \-a
This adds the normal
.B irc
server list to the command line list of
.B irc
servers.
.TP
.BI \-v
Print the version and release date of
.I ircII
and exit.
.TP
.BI \-q
Start up
.B irc
quickly -- don't load the IRCRC file.
.SH "DETAILED DESCRIPTION"
.SS "The Screen:"
The
screen is split into two parts, separated by an inverse-video
status line (if supported).
The upper (larger) part of the screen displays responses from the
.I IRC
server.
The lower part of the screen (a single line) accepts keyboard input.
.LP
Some terminals do not support certain features required by
.IR ircII ,
in which case you receive a message stating this.
If this occurs, try changing the terminal type or run
.I ircII
with the
.B -d
option.
.SS "Irc Commands:"
Any line beginning with the slash character '/' is regarded as an
.I ircII
command (the command character may be changed; type '/help set cmdchar').
Any line not beginning with this character is treated as a message to
be sent to the current channel.
To produce a listing of commands, type '/help ?'.
To receive information about the commands type '/help
.B <command> '.
.SS "The .ircrc File:"
When
.I ircII
is executed, it checks the user's home directory for a
.I \&.ircrc
file, executing the commands in the file. Commands in this file do not
need to have a leading slash character '/'
This allows predefinition of aliases and other features.
.SH EXAMPLES
.TP
.B "irc -c 128 -p 5555"
Connect
.I IRC
to port number 5555 of the default host and enter on channel number 128.
.TP
.B "irc Mermaid"
Use the nickname "Mermaid".
.TP
.B "irc Mermaid server1:5000 server2::passwd server3"
Use the nickname "Mermaid" and the modified server list.
.TP
.B "irc -d"
Use dumb mode.
.TP
.B "irc -f"
Allow use of ^S/^Q to stop/start screen display.
.TP
.B "irc -e elisa"
Interface
.I IRC
with a program called
.IR elisa .
.LP
.B "setenv IRCNICK Mermaid"
.br
.B "setenv IRCNAME \"The one and only :)\""
.TP
.B irc
Set the username (if not specified elsewhere) to "Mermaid".
The user's name (when provided inside parentheses in response to a
WHOIS command) is set to "The one and only :)".
.SH FILES
.TP 2.2i
.I .../bin/ircII
the executable program
.TP
~/.ircrc
default initialization file
.TP
~/.irc/
directory you can put your own
.I ircII
scripts into, that can then be loaded with /load
.TP
.I .../lib/irc/
directory containing message-of-the-day, master initialization, help files and 
.I ircII
scripts
.SH "THE HELP FILES"
All of the
.B ircII
commands are fully described in the help files package.  The best way to
start here is with the
.IR /HELP\ ?
command as this prints a listing of all available help files.
.SH "SIGNALS"
.I ircII
handles the following signals
.TP
.B SIGUSR1
Closes all
.I DCC
connections and
.I EXEC'ed
processes.
.TP
.B SIGUSR2
Drops
.I ircII
back to the command line.
.SH "ENVIRONMENT VARIABLES"
It can be helpful to predefine certain variables in
in the
.IR \&.cshrc ,
.IR \&.profile ,
or
.IR \&.login
file:
.TP
.B IRCNICK
The user's
.I IRC
nickname.
.TP
.B IRCNAME
The user's
.I IRC
realname (otherwise retreived from
.IR /etc/passwd )
.TP
.B IRCSERVER
The default
.I IRC
server(s) (see server
.B option
for details)
.TP
.B HOME   
Overrides the default home path in
.IR /etc/passwd .
.TP
.B TERM   
The type of terminal in use.
.fi
.SH "SEE ALSO"
irc(1),
ircd(8)
.SH BUGS
Please notify the current developer of the software of any bugs in
current versions.
.SH AUTHORS
Program written by Michael Sandrof (ms5n+@andrew.cmu.edu).
Now being maintained by Matthew Green (mrg@mame.mu.oz.au)
Names of contributors and contact address can be retrieved with the
.B /info command.
This manual page written by Darren Reed (avalon@coombs.anu.EDU.AU),
revised by R. P. C. Rodgers (rodgers@maxwell.mmwb.ucsf.edu),
by the lynX, and by Matthew Green (mrg@mame.mu.oz.au).
.\" end of man page
